name = "PyDislocDyn_Fortranlibrary"
version = "20260528"
license = "LICENSE.md"
author = "Daniel N. Blaschke"
maintainer = "40176390+dblaschke-LANL@users.noreply.github.com"
copyright = "Copyright 2018, Triad National Security, LLC"
homepage = "https://github.com/dblaschke-LANL/PyDislocDyn"

[dependencies]
#stdlib = "*"
openmp = "*"

#[dev-dependencies]
#test-drive.git = "https://github.com/fortran-lang/test-drive"
#test-drive.tag = "v0.6.0"

[features]
release.gfortran.flags = "-O3 -march=native"
release.flang.flags = "-O3 -march=native"

[library]
type = ["shared", "static"]
source-dir = "pydislocdyn"

[[executable]]
name = "dislocdyn"
source-dir = "app"
main = "dislocdyn.f90"

[[test]]
name = "runtests"
source-dir = "testing"
main = "runtests.f90"

[install]
library = true

[extra.ford]
project = "PyDislocDyn_Fortranlibrary"
year = "2018-2026"
summary  = 'A Fortran library/program to calculate dislocation drag from phonon wind as well as dislocation limiting velocities.'
project_github  = "https://github.com/dblaschke-LANL/PyDislocDyn"
src_dir = ["./pydislocdyn","./app"]
