[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "PyDislocDyn"
version = "1.4.0+dev"
authors = [
  { name="Daniel N. Blaschke", email="40176390+dblaschke-LANL@users.noreply.github.com" },
]
description = "PyDislocDyn is a suite of python programs designed to perform various calculations for basic research in dislocation dynamics in metals with various crystal symmetries in the continuum limit."
readme = {file = "readme.md", content-type = "text/markdown"}
license = {file = "LICENSE.md"}
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD License",
    "Private :: Do Not Upload",
]
dependencies = [
  "numpy>=2.2",
  "scipy>=1.13",
  "sympy>=1.13",
  "matplotlib>=3.8",
  "pandas>=2.2",
  "jinja2>=3.1",
]
[project.optional-dependencies]
fast = [
  "numba>=0.61",
  "joblib>=1.2",
  "threadpoolctl>=3.1"
]
dev = [
  "pytest>=8.3"
]
yaml = [
  "pyyaml>=6.0"
]
all = [
  "pydislocdyn[fast,dev,yaml]",
]

[project.urls]
Homepage = "https://github.com/dblaschke-LANL/PyDislocDyn"
Issues = "https://github.com/dblaschke-LANL/PyDislocDyn/issues"
