name: CI

on:
  push:
    paths:
      - '**.f90'
      - '**.toml'
      - '**.yml'

jobs:
  RunTests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        toolchain:
          - {compiler: gcc, version: 'latest'}
          - {compiler: intel, version: '2026.1'}
          - {compiler: nvidia-hpc, version: 'latest'}
          - {compiler: lfortran, version: '0.66.0'}
          - {compiler: aocc, version: '5.2.0'}
        exclude:
          - os: macos-latest
            compiler: nvidia-hpc
          - os: macos-latest
            compiler: aocc
          - os: windows-latest
            compiler: nvidia-hpc
          - os: windows-latest
            compiler: aocc
    steps:
      - uses: fortran-lang/setup-fortran@v1
        id: setup-fortran
        with:
          compiler: ${{ matrix.toolchain.compiler }}
          version: ${{ matrix.toolchain.version }}
      - name: Setup Fortran Package Manager
        uses: fortran-lang/setup-fpm@v10
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run tests
        run: |
          ${{ env.FC }} fpm test --profile release
